web/authuser/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "authuser"
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('home/', views.home, name='home'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('edit/', views.edit_profile, name='edit_profile'),
]

web/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"
urlpatterns = [
    # path("", views.index, name="index"),
    # path("<str:room_name>/", views.room, name="room"),
    path("dm/<str:other_user>/", views.private_room, name="private_room"),
]

web/friend/urls.py
# urls.py
from django.urls import path
from .views import *

app_name = "friend"
urlpatterns = [
    path('send_friend_request/<str:username>/', send_friend_request, name='send_friend_request'),
    path('accept_request/<str:username>/', accept_request, name='accept_request'),
    path('decline_request/<str:username>/', decline_request, name='decline_request'),
    path('cancel_request/<str:username>/', cancel_request, name='cancel_request'),
    path('remove_friend/<str:username>/', remove_friend, name='remove_friend'),
]

web/game/urls.py
from django.urls import path

from . import views

app_name = "game"
urlpatterns = [
    path("1v1/<str:other_user>/", views.remote_room, name="remote_room"),
    path("local/", views.local_room, name="local_room"),
    path("ending/", views.game_ending, name="game_ending"),
]

web/src/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

web/web/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls")),
    path('authuser/', include("authuser.urls")),
    path('chat/', include("chat.urls")),
    path('friend/', include("friend.urls")),
    path('game/', include("game.urls")),
    path('oauth/', include("customoauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/authuser/models.py
from django.contrib.auth.models import AbstractUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone
from friend.models import FriendList
from game.models import GameStats


class CustomUserManager(UserManager):
    def __create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("Email is required")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", False)
        extra_fields.setdefault("is_staff", False)

        return self.__create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_staff", True)

        return self.__create_user(email, password, **extra_fields)


class User(AbstractUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True)
    tournament_name = models.CharField(max_length=255, blank=True, default="")
    avatar = models.ImageField(null=True, blank=True, upload_to="avatars/", default="avatars/default_avatar.jpg")

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    friends_list = models.OneToOneField(FriendList, on_delete=models.CASCADE, null=True, blank=True, related_name="user_friend_list")
    game_stats = models.OneToOneField(GameStats, on_delete=models.CASCADE, null=True, blank=True, related_name="user_game_stats")

    objects = CustomUserManager()

    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.username

    def get_profile_page_info(self):
        return {
            "avatar": self.avatar if self.avatar else "/media/avatars/default_avatar.jpg",
            "username": self.username,
            "email": self.email,
            "tournament_name": self.tournament_name,
            "date_joined": self.date_joined,
            "last_login": self.last_login,
            "status": self.is_active,
        }

    def get_all_other_users(self):
        return User.objects.filter(is_staff=False).exclude(username=self.username)

web/authuser/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .models import User
from friend.models import FriendList
from game.models import GameStats


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "username", 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']

        if commit:
            user.save()
            FriendList.objects.create(user=user)
            user.friends_list = FriendList.objects.get(user=user)
            user.save()
            GameStats.objects.create(user=user)
            user.game_stats = GameStats.objects.get(user=user)
            user.save()
        return user


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "username", "tournament_name", )


class AvatarChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("avatar",)

web/authuser/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from .forms import CustomUserCreationForm, CustomUserChangeForm, AvatarChangeForm
from friend.models import FriendList, FriendRequest
from django.conf import settings
from .models import User
from game.models import GameStats


def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(settings.HOME_URL)
    else:
        form = CustomUserCreationForm()

    return render(request, "authuser/register.html", {"form": form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Login successful.')
                return redirect(settings.HOME_URL)  # Change 'home' to your desired URL
            else:
                messages.error(request, 'Invalid login credentials.')
    else:
        form = AuthenticationForm()

    return render(request, 'authuser/login.html', {'form': form})


@login_required
def home(request):
    return render(request,
                  "authuser/home.html",
                  {
                      "current_user": request.user.get_short_name(),
                      "friend_list": FriendList.objects.get(user=request.user),
                      "pending_requests_info": FriendRequest().requests_info(request.user),
                      "all_users": request.user.get_all_other_users()})


@login_required
def profile(request, username):
    if username == request.user.username:
        return render(request,
                      "authuser/self-profile.html",
                      {
                          "current_user": request.user.get_short_name(),
                          "info": User.objects.get(username=username).get_profile_page_info(),
                          "stats": GameStats.objects.get(user=request.user).get_game_stats(),
                          "game_history": GameStats.objects.get(user=request.user).get_game_history(),
                      })
    return render(request,
                  "authuser/profile.html",
                  {
                      "current_user": request.user.get_short_name(),
                      "target_user": username,
                      "info": User.objects.get(username=username).get_profile_page_info(),
                      "stats": GameStats.objects.get(user=User.objects.get(username=username)).get_game_stats(),
                      "game_history": GameStats.objects.get(user=User.objects.get(username=username)).get_game_history(),
                      "name_for_room": request.user.username + ":" + username,
                  })


@login_required
def edit_profile(request):
    if request.method == "POST":
        info_form = CustomUserChangeForm(request.POST, instance=request.user)
        avatar_form = AvatarChangeForm(request.POST, request.FILES, instance=request.user)
        if info_form.is_valid() and avatar_form.is_valid():
            info_form.save()
            avatar_form.save()
            return redirect('authuser:profile', username=request.user.username)
    else:
        info_form = CustomUserChangeForm(instance=request.user)
        avatar_form = AvatarChangeForm(instance=request.user)

    return render(request, "authuser/edit_profile.html", {"form": info_form, "image_form": avatar_form})

web/authuser/templates/authuser/base.html
<!-- authuser/templates/authuser/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Site{% endblock %}</title>
    <!-- Add your CSS and Bootstrap links here -->
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

web/authuser/templates/authuser/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PROFILE PAGE - EDIT</title>
</head>
<body>
    <!-- edit_profile.html -->
    <form method="post" action="{% url 'authuser:edit_profile' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ image_form.as_p }}
        <button type="submit">Save changes</button>
    </form>
</body>
</html>

web/authuser/templates/authuser/home.html
<!-- authuser/templates/authuser/home.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>

    <h1>Welcome to the Home Page, <a href="{% url 'authuser:profile' username=current_user %}"> {{ current_user }}</a></h1>

    <h2>Your Friends:</h2>
    <ul>
        {% for friend in friend_list.friends.all %}
            <a href="{%  url 'authuser:profile' username=friend.username %}">
                <button>{{ friend.username }}</button>
            <br>
            </a>
        {% endfor %}
    </ul>

    <h2>Pending Friend Requests:</h2>
    <ul>
        {% for request_info in pending_requests_info %}
            {% if request_info.sender.username == current_user %}
                <li>Request sent to: {{ request_info.receiver.username }} at {{ request_info.timestamp }}</li>
                <form method="post" action="{% url 'friend:cancel_request' username=request_info.receiver.username %}">
                    {% csrf_token %}
                    <button type="submit">CANCEL</button>
                 </form>
            {% else %}
                <li>Request received from: {{ request_info.sender.username }} at {{ request_info.timestamp }}</li>
                <form method="post" action="{% url 'friend:accept_request' username=request_info.sender.username %}">
                    {% csrf_token %}
                    <button type="submit">ACCEPT</button>
                 </form>
                <form method="post" action="{% url 'friend:decline_request' username=request_info.sender.username %}">
                    {% csrf_token %}
                    <button type="submit">DECLINE</button>
                 </form>
            {% endif %}
        {% endfor %}
    </ul>



    <h2>Users:</h2>
    <ul>
        {% for user in all_users.all %}
            <a href="{% url 'authuser:profile' username=user.username %}">
                <button>{{ user.username }}</button>
                <br>
            </a>
        {% endfor %}
    </ul>

    <a href="{%  url 'game:local_room' %}">
                <button>Local Game</button>
            <br>
    </a>

    <form method="post" action="{% url 'authuser:logout' %}">
        {% csrf_token %}
        <button type="submit">LOGOUT</button>
    </form>
    <!-- Add your content here -->

</body>
</html>

web/authuser/templates/authuser/login.html
<!-- authuser/templates/authuser/registration/login.html -->

{% extends 'authuser/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
    <form method="get" action="{% url 'oauth-login' %}">
        <button type="submit">Login with 42 OAuth2</button>
    </form>
    <p>Don't have an account? <a href="{% url 'authuser:register' %}">Register</a></p>
{% endblock %}

web/authuser/templates/authuser/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PROFILE PAGE</title>
</head>
<body>
    <h1>{{ target_user }}</h1>
        <a href="{%  url 'authuser:home' %}">
            <button>HOME</button>
            <br>
        </a>
    <img src="{{ info.avatar.url }}" alt="Avatar" width="200" height="200">
    <h2>Info:</h2>
    <ul>
        <li>Username: {{ info.username }}</li>
        <li>Tournament Name: {{ info.tournament_name }}</li>
        <li>Date Joined: {{ info.date_joined }}</li>
        <li>Last Login: {{ info.last_login }}</li>
        <li>Status: {{ info.status }}</li>
    </ul>
    <h2>Stats:</h2>
    <ul>
        <li>Wins: {{ stats.wins }}</li>
        <li>Losses: {{ stats.losses }}</li>
        <li>Games Played: {{ stats.games_played }}</li>
        <li>Tournaments Won: {{ stats.tournaments_won }}</li>
        <li>Tournaments Played: {{ stats.tournaments_played }}</li>
    </ul>
    <h2>Game History: </h2>
    <ul>
        {% for game in game_history %}
            <li>{{ game }}
            {% if game.winner.username == target_user %}
                VICTORY
            {% else %}
                DEFEAT
            {% endif %}
            </li>
            <br>
        {% endfor %}
    </ul>
    <form method="post" action="{% url 'friend:send_friend_request' username=target_user %}">
        {% csrf_token %}
        <button type="submit">Add Friend</button>
    </form>
    <form method="post" action="{% url 'friend:remove_friend' username=target_user %}">
        {% csrf_token %}
        <button type="submit">Remove Friend</button>
    </form>
    <a href="{%  url 'chat:private_room' other_user=target_user %}">
        <button>CHAT</button>
        <br>
    </a>
    <a href="{%  url 'game:remote_room' other_user=target_user %}">
        <button>GAME</button>
        <br>
    </a>
</body>
</html>

web/authuser/templates/authuser/register.html
<!-- authuser/templates/authuser/registration/register.html -->
{% extends 'authuser/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
    <p>Already have an account? <a href="{% url 'authuser:login' %}">Login</a></p>
{% endblock %}

web/authuser/templates/authuser/self-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PROFILE PAGE</title>
</head>
<body>
    <h1>{{ current_user }}</h1>
        <a href="{%  url 'authuser:home' %}">
            <button>HOME</button>
            <br>
        </a>
    <img src="{{ info.avatar.url }}" alt="Avatar" width="200" height="200">
    <h2>Info:</h2>
    <ul>
        <li>Username: {{ info.username }}</li>
        <li>Email: {{ info.email }}</li>
        <li>Tournament Name: {{ info.tournament_name }}</li>
        <li>Date Joined: {{ info.date_joined }}</li>
        <li>Last Login: {{ info.last_login }}</li>
    </ul>
    <h2>Stats:</h2>
    <ul>
        <li>Wins: {{ stats.wins }}</li>
        <li>Losses: {{ stats.losses }}</li>
        <li>Games Played: {{ stats.games_played }}</li>
        <li>Tournaments Won: {{ stats.tournaments_won }}</li>
        <li>Tournaments Played: {{ stats.tournaments_played }}</li>
    </ul>
    <h2>Game History: </h2>
    <ul>
        {% for game in game_history %}
            <li>{{ game }}
            {% if game.winner.username == current_user %}
                VICTORY
            {% else %}
                DEFEAT
            {% endif %}
            </li>
            <br>
        {% endfor %}
    </ul>
<a href="{%  url 'authuser:edit_profile' %}">
    <br>
    <button>EDIT</button>
    <br>
</a>
</body>
</html>