web/authuser/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "authuser"
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('home/', views.home, name='home'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('edit/', views.edit_profile, name='edit_profile'),
]

web/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"
urlpatterns = [
    # path("", views.index, name="index"),
    # path("<str:room_name>/", views.room, name="room"),
    path("dm/<str:other_user>/", views.private_room, name="private_room"),
]

web/game/urls.py
from django.urls import path

from . import views

app_name = "game"
urlpatterns = [
    path("1v1/<str:other_user>/", views.remote_room, name="remote_room"),
    path("local/", views.local_room, name="local_room"),
    path("ending/", views.game_ending, name="game_ending"),
]

web/src/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

web/web/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls")),
    path('authuser/', include("authuser.urls")),
    path('chat/', include("chat.urls")),
    path('friend/', include("friend.urls")),
    path('game/', include("game.urls")),
    path('oauth/', include("customoauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/chat/models.py
from django.db import models
from django.conf import settings


class Chat(models.Model):
    content = models.CharField(max_length=1000)
    timestamp = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey("ChatRoom", on_delete=models.CASCADE)
    username = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.room} - {self.user.username} - {self.content}"


class ChatRoom(models.Model):
    name = models.CharField(max_length=255)
    user1 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="chat_user1", null=True)
    user2 = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="chat_user2", null=True)

    def __str__(self):
        return f"{self.name}"

web/chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Chat, ChatRoom
from authuser.models import User
import secrets
import string


def generate_random_string(length):
    characters = string.ascii_letters + string.digits + "_"
    random_string = ''.join(secrets.choice(characters) for _ in range(length))
    return random_string


@login_required
def private_room(request, other_user):
    chats = []
    other_user_obj = User.objects.get(username=other_user)
    if ChatRoom.objects.filter(user1=request.user, user2=other_user_obj).first():
        room_obj = ChatRoom.objects.filter(user1=request.user, user2=other_user_obj).first()
        chats = Chat.objects.filter(room=room_obj).order_by('timestamp')
    elif ChatRoom.objects.filter(user2=request.user, user1=other_user_obj).first():
        room_obj = ChatRoom.objects.filter(user2=request.user, user1=other_user_obj).first()
        chats = Chat.objects.filter(room=room_obj).order_by('timestamp')
    else:
        room_obj = ChatRoom(user1=request.user, user2=other_user_obj, name=generate_random_string(9))
        room_obj.save()
    return render(request, "chat/room.html", {
        "room_name": room_obj.name,
        "chats": chats,
        "sender": request.user.username,
        "target_user": other_user,
    })

web/chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

web/chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>

<head>
    <style>
        #chat-log {
            width: 100%;
            height: 150px;
            padding: 12px 20px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            background-color: #7c7a7a;
            font-size: 16px;
            color: #4ed540;
        }
    </style>
</head>

<body>
<a href="{% url 'authuser:profile' username=target_user %}">
                <button>{{ target_user }}'s profile</button>
                <br>
</a>
<textarea id="chat-log" cols="100" rows="20"></textarea><br>
<input id="chat-message-input" type="text" size="100"><br>
<input id="chat-message-submit" type="button" value="Send">
{{ room_name|json_script:"room_name" }}
<script>
    let message;
    let username;
    let day;
    let hour;
    let formattedMessage;
    {% for chat in chats.all %}
        message = "{{ chat.content|safe }}";
        username = "{{ chat.username|safe }}";
        day = "{{ chat.timestamp|date:'Y-m-d' }}";
        hour = "{{ chat.timestamp|date:'H:i' }}";
        formattedMessage = `[${day} ${hour}][${username}]: ${message}`;
        document.querySelector('#chat-log').value += (formattedMessage + '\n');
        document.querySelector('#chat-log').scrollTop = document.querySelector('#chat-log').scrollHeight;
    {% endfor %}
</script>

<script>
    const roomName = JSON.parse(document.getElementById('room_name').textContent);

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        const timestamp = new Date(data.timestamp);
        const day = `${timestamp.getUTCFullYear()}-${padZero(timestamp.getUTCMonth() + 1)}-${padZero(timestamp.getUTCDate())}`
        const hour = `${padZero(timestamp.getUTCHours())}:${padZero(timestamp.getUTCMinutes())}`;
        const formattedMessage = `[${day} ${hour}][${data.username}]: ${data.message}`;
        document.querySelector('#chat-log').value += (formattedMessage + '\n');
    };

    function padZero(num) {
        return num.toString().padStart(2, '0');
    }

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.key === 'Enter') {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));
        messageInputDom.value = '';
    };
</script>
<a href="{%  url 'authuser:home' %}">
    <br>
    <button>HOME</button>
</a>
<a href="{%  url 'game:remote_room' other_user=target_user %}">
        <button>GAME</button>
</a>


</body>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>

</html>